### ISSUE TITLE
Table crashes marimo

### ISSUE THREAD

**Issue by fuenfundachtzig** [marimo-team/marimo#1056] opened 2024-04-03 19:44 UTC
### Describe the bug

When I try this line
```
mo.ui.table([1, 2])
```
the server (0.3.8) crashes with "Task exception was never retrieved". 

### Environment

{
  "marimo": "0.3.8",
  "OS": "Linux",
  "OS Version": "5.4.0-174-generic",
  "Processor": "x86_64",
  "Python Version": "3.8.10",
  "Binaries": {
    "Browser": "123.0.6312.86",
    "Node": "v18.20.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.4.0",
    "jedi": "0.18.0",
    "markdown": "3.5",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.8.0",
    "black": "23.3.0"
  }
}

### Code to reproduce

import marimo as mo
mo.ui.table([1, 2])

**Comment by akshayka** [comment] 2024-04-03 21:09
Thanks for filing this issue. Somehow I'm unable to reproduce it. The table renders just fine for me. Perplexing ...

**Comment by fuenfundachtzig** [comment] 2024-04-04 05:58
Yes, it would have been surprising if such a simple thing had gone unnoticed. I'll try to find out the root cause.

**Comment by mscolnick** [comment] 2024-04-04 15:56
@fuenfundachtzig , if you run `marimo -d edit`, this runs in debug-mode which has more logging information

**Comment by fuenfundachtzig** [comment] 2024-04-06 12:29
(Updated to 0.3.10)
<details>
  <summary>
    Debug output
  </summary>

```
[D 240406 14:23:32 ops:54] Broadcasting op: CompletedRun()
INFO:     127.0.0.1:41440 - "POST /api/kernel/run HTTP/1.1" 200 OK
[D 240406 14:24:34 runtime:1411] received request ExecuteMultipleRequest(execution_requests=[ExecutionRequest(cell_id='bJsr', code='mo.ui.table([1, 2])')])
[D 240406 14:24:34 runtime:533] Current set of errors: {}
[D 240406 14:24:34 runtime:380] registered cell bJsr
[D 240406 14:24:34 runtime:381] parents: {'Hbol'}
[D 240406 14:24:34 runtime:382] children: set()
[D 240406 14:24:34 runtime:409] graph:
    	cell id bJsr
    	parents {'Hbol': set(), 'bJsr': {'Hbol'}}
    	children {'Hbol': {'bJsr'}, 'bJsr': set()}
    	siblings {'Hbol': set(), 'bJsr': set()}
[D 240406 14:24:34 runtime:567] After mutation, syntax errors {}
[D 240406 14:24:34 runtime:568] Semantic errors {}
[D 240406 14:24:34 runtime:612] Final set of errors, after pruning valid cells: {}
[D 240406 14:24:34 ops:54] Broadcasting op: Variables(variables=[VariableDeclaration(name='mo', declared_by=['Hbol'], used_by=['bJsr'])])
[D 240406 14:24:34 runtime:733] preparing to evaluate cells {'bJsr'}
[D 240406 14:24:34 ops:54] Broadcasting op: CellOp(cell_id='bJsr', output=None, console=None, status='queued', timestamp=1712406274.9399412)
[D 240406 14:24:34 ops:54] Broadcasting op: RemoveUIElements(cell_id='bJsr')
[D 240406 14:24:34 runtime:765] final set of cells to run ['bJsr']
[D 240406 14:24:34 runtime:775] running cell bJsr
[D 240406 14:24:34 ops:54] Broadcasting op: CellOp(cell_id='bJsr', output=None, console=[], status='running', timestamp=1712406274.9403539)
[D 240406 14:24:36 sessions:289] Closing session because kernel died

        The Python kernel died unexpectedly.

INFO:     connection closed
[D 240406 14:24:36 ws:362] Websocket terminated with CancelledError
Task exception was never retrieved
future: <Task cancelling name='Task-24' coro=<WebsocketHandler.on_start.<locals>._heartbeat() done, defined at .../marimo/marimo/_server/api/endpoints/ws.py:370> exception=SystemExit()>
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../marimo/marimo/_cli/cli.py", line 217, in edit
    start(
  File ".../marimo/marimo/_server/start.py", line 118, in start
    server.run()
  File "~/.local/lib/python3.8/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File ".../marimo/marimo/_server/api/endpoints/ws.py", line 373, in _heartbeat
    check_alive()
  File ".../marimo/marimo/_server/sessions.py", line 294, in _check_alive
    sys.exit()
SystemExit
```

</details>

**Comment by fuenfundachtzig** [comment] 2024-04-09 20:45
Today encountered this (apparently, I ran pytest for the first time...):

<details>
  <summary>
    pytest output
  </summary>

```
...
tests/_plugins/ui/_impl/test_dictionary.py ....                                                                                                                                                                                [ 44%]
tests/_plugins/ui/_impl/test_input.py .............                                                                                                                                                                            [ 47%]
tests/_plugins/ui/_impl/test_table.py Fatal Python error: Illegal instruction

Thread 0x00007f0ddb37a700 (most recent call first):
  File "[path]/marimo/marimo/_messaging/streams.py", line 103 in _forward_os_stream
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f0dd0c34700 (most recent call first):
  File "[path]/marimo/marimo/_messaging/streams.py", line 103 in _forward_os_stream
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f0de0f90740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1166 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "[path]/marimo/.venv/lib/python3.8/site-packages/polars/__init__.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "[path]/marimo/marimo/_plugins/ui/_impl/table.py", line 270 in _normalize_data
  File "[path]/marimo/tests/_plugins/ui/_impl/test_table.py", line 26 in test_normalize_data
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/python.py", line 1792 in runtest
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/main.py", line 350 in pytest_runtestloop
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/main.py", line 325 in _main
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/main.py", line 271 in wrap_session
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/main.py", line 318 in pytest_cmdline_main
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "[path]/marimo/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 169 in main
  File "[path]/marimo/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 192 in console_main
  File "[path]/marimo/.venv/bin/pytest", line 8 in <module>
make: *** [Makefile:68: py-test] Illegal instruction (core dumped)

```

</details>

**Comment by akshayka** [comment] 2024-04-09 23:56
Closing — we discussed in Discord, and this was due to a broken installation of Polars.

**Closed by akshayka** 2024-04-09 23:56 UTC
Labels: bug

**Comment by fuenfundachtzig** [comment] 2024-04-10 15:58
Additional information: it's not a broken installation of Polars but rather that Polars requires AVX2. Older versions of polars such as 0.19.12 will just crash with "Illegal instruction (core dumped)". Newer versions give a warning if AVX2 is not available before crashing. As an alternative, [Polars-LTS-CPU](https://pypi.org/project/polars-lts-cpu/) can be installed which is compiled without AVX.
