### ISSUE TITLE
ctrl+[ doesn't acts as "esc" in vim mode

### ISSUE THREAD

**Issue by MarcoGorelli** [marimo-team/marimo#2194] opened 2024-09-02 16:18 UTC
### Describe the bug

If I enable vim keybindings in Marimo, then I can't use `ctrl+[` as an alias for `esc`. However, it should technically be supported: https://vim.fandom.com/wiki/Avoid_the_escape_key

### Environment

{
  "marimo": "0.8.7",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.4.4",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.4",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.6.3"
  }
}

### Code to reproduce

n/a 😉 

So I'm going to use this space to say - I friggin' love Marimo, thank you so much for the work you're doing here 🙏 😍

**Comment by mscolnick** [comment] 2024-09-02 18:34
Duplicate of https://github.com/marimo-team/marimo/issues/558

I was unable to repro on mac (my dev setup) so I couldn't get a proper fix in. We can take another look, though.

**Closed** 2024-09-02 19:28 UTC
Labels: bug
