### ISSUE TITLE
stuck in a "Run in a sandboxed venv containing this notebook's dependencies?" loop

### ISSUE THREAD

**Issue by foxcroftjn** [marimo-team/marimo#2443] opened 2024-09-28 19:35 UTC
### Describe the bug

When I run the command `marimo edit --sandbox notebook.py`, I get stuck in the following loop:

```
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmpf76pg5zd.txt marimo edit temp.py
This notebook has inlined package dependencies.
Run in a sandboxed venv containing this notebook's dependencies? [Y/n]: y
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmpm4qbrsyn.txt marimo edit temp.py
This notebook has inlined package dependencies.
Run in a sandboxed venv containing this notebook's dependencies? [Y/n]: y
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmpywz9invj.txt marimo edit temp.py
This notebook has inlined package dependencies.
Run in a sandboxed venv containing this notebook's dependencies? [Y/n]: 
```

I shouldn't be prompted in the first place, since I specified the flag `--sandbox` when running the marimo command.

### Environment

{
  "marimo": "0.8.21",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "",
  "Python Version": "3.12.5",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.17.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11",
    "ruff": "0.6.8",
    "starlette": "0.39.1",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.31.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}

### Code to reproduce

I have been able to reproduce this so long as the marimo notebook contains at least one inline dependency. For example:

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "polars==1.8.2",
# ]
# ///

import marimo

__generated_with = "0.8.21"
app = marimo.App(width="medium")


@app.cell
def __():
    import polars as pl
    return (pl,)


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment] 2024-09-28 19:52
Oh this does look like a regression from https://github.com/marimo-team/marimo/pull/2412

Can you downgrade in the meantime, we will get a fix out for this

**Comment by foxcroftjn** [comment] 2024-09-28 20:08
I've tried downgrading marimo, and surprisingly this doesn't fix the issue. I still get stuck in the prompt loop even when I'm running older versions of marimo (I've tested everything back to 0.8.4).

I can make do for now by saying "no" in the prompting loop, which then appears to correctly run my script in a sandbox anyways. My guess is that marimo is failing to recognize when it is already running in a sandbox, which triggers the prompt, which in turn (when I say yes) spawns a new sandbox that marimo again fails to recognize (retriggering the prompt).

Perhaps there has been a change in `uv` that has caused marimo to stop recognizing that it is in a sandbox? That would explain why downgrading marimo doesn't fix the problem. I haven't been able to fix this issue by downgrading `uv` either though, so this is just speculation on my part.

**Comment by mscolnick** [comment] 2024-09-28 20:17
Actually - I bet the issue is that it ends up installing the latest version of marimo in the sandbox, reverting back to the broken version. 

I think you may also be able to do "--yes" and that hopefully gets passed to the sandbox version.

**Comment by foxcroftjn** [comment] 2024-09-28 20:23
> Actually - I bet the issue is that it ends up installing the latest version of marimo in the sandbox, reverting back to the broken version.

That makes sense to me!

> I think you may also be able to do "--yes" and that hopefully gets passed to the sandbox version.

That flag was only introduced in marimo==0.8.21, so I can't use it with older versions of marimo. If I use it with the newest version of marimo, I get stuck in the same loop but without the prompt:

```
$ marimo --yes edit --sandbox notebook.py
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmp9jrbiqzh.txt marimo --yes edit notebook.py
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmpfqxdfkkb.txt marimo --yes edit notebook.py
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmppxrh_hw6.txt marimo --yes edit notebook.py
etc...
```

**Comment by mscolnick** [comment] 2024-09-28 21:04
Ah yea you are right. Ok, so sandbox is just broken. We will fix this asap, apologies for the inconvenience.

**Comment by akshayka** [comment] 2024-09-29 00:23
@foxcroftjn we've released a new version that should hopefully fix this. Can you let us know if it's working for you?

**Comment by mscolnick** [comment] 2024-09-30 13:25
Going to close this issue. It should be fixed on the latest marimo release, but please reach out otherwise.

**Closed by mscolnick** 2024-09-30 13:25 UTC
Labels: bug

**Comment by foxcroftjn** [comment] 2024-09-30 19:17
> @foxcroftjn we've released a new version that should hopefully fix this. Can you let us know if it's working for you?

Sorry for the slow response. The fix is working for me! Thank you!
