### ISSUE TITLE
no negative values allowed in mo.ui.table

### ISSUE THREAD

**Issue by pHenney** [marimo-team/marimo#1173] opened 2024-04-19 03:33 UTC
### Describe the bug

using plotly to return a list of dicts when values in graph are highlighted.
these values are used in calculations that are then output to a table mo.ui.table displayed under the graph.
if the values are negative in the table (i.e. calculating rate of change etc), a "math domain error" is returned and the field in the table is left blank, along with all successive fields in the table.
I have troubleshooted with print statements and it should be fine. issue goes away when I introduce abs(x)

### Environment

{
  "marimo": "0.4.1",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": ",
  "Python Version": "3.11.8",
  "Binaries": {
    "Browser": "",
    "Node": "v20.11.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "5.7.0",
    "jedi": "0.19.1",
    "markdown": "3.5.2",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.3",
    "uvicorn": "0.28.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.8.0",
    "black": "24.2.0"
  }
}

### Code to reproduce

df = selection_to_dataframe(plot.value)
table = mo.ui.table(df)

where selectrion to dataframe disseminates data into values for the dataframe

**Comment by mscolnick** [comment] 2024-04-19 13:32
I cannot repro this: https://marimo.app/l/yq95qy 
Can you include a full snippet of code with the reproduction?

**Comment by mscolnick** [comment] 2024-04-23 21:01
Closing as we cannot reproduce with the given code

**Closed by mscolnick** 2024-04-23 21:01 UTC
Labels: bug
