### ISSUE TITLE
`asyncio.run` crashes with `RuntimeError: asyncio.run() cannot be called from a running event loop`

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#1746] opened 2024-07-07 10:04 UTC
### Describe the bug

Creating a notebook with a single cell, and then running the following code:
```python
import asyncio

async def f():
    print('hi')

asyncio.run(f())
```
will crash with the error:
```
RuntimeError: asyncio.run() cannot be called from a running event loop
```

Presumably Marimo itself happens to use `asyncio` as part of its own implementation, and that detail is leaking into userspace.

### Proposed fix

I believe the standard fix for this scenario -- having async code call sync code call async code -- is for the intermediate sync code to call its client code in a separate thread. For example, this works:
```python
import threading

def cell():
    import asyncio

    async def f():
        print('hi')

    asyncio.run(f())

t = threading.Thread(target=cell)
t.start()
t.join()
```
so it would be nice if Marimo would automatically do this for all cells!

### Environment

```
{
  "marimo": "0.6.8",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.11.9",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "v21.6.2"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "9.4",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "24.4.2"
  }
}
```

**Comment by akshayka** [comment] 2024-07-08 19:02
Thanks for the detailed issue!

> Presumably Marimo itself happens to use asyncio as part of its own implementation, and that detail is leaking into userspace.

In fact it's not a leak, but intentional. This makes it possible to use async libraries with top-level await, meaning for example

```python
import asyncio

async def f():
    print('hi')

await f()
```

will just work in marimo.

Originally we didn't support top-level await -- had similar concerns to you -- but it was requested by many of our users.

For precedence, IPython (which we don't use) enabled top-level await 6 years ago: https://blog.jupyter.org/ipython-7-0-async-repl-a35ce050f7f7.

In cases where nested event loops are required, I believe that `nest-asyncio` can be used: https://pypi.org/project/nest-asyncio/

**Comment by mscolnick** [comment] 2024-07-11 15:10
Going to close this, as this is by design to support to level await

**Closed by mscolnick** 2024-07-11 15:10 UTC
Labels: bug
